name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  python:
    name: Python
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          # Install packages
          sudo apt-get update
          sudo apt-get install -y libpq-dev python-dev-is-python3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - working-directory: app
        run: |
          # Install dependencies
          pip install -r ./requirements.txt --disable-pip-version-check
      - working-directory: app/src/
        run: |
          # Run main.py
          python main.py || \
            echo "App failing!"

  # oc:
  #   name: OpenShift
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Execute OC Test
  #       run: |
  #         oc version
  #         oc login --token=${{ secrets.oc_token }} --server=${{ vars.oc_server }}
  #         oc project ${{ secrets.OC_NAMESPACE }} # Safeguard!
  #         oc whoami


  results:
    name: PR Results
    # needs: [python, oc]
    needs: [python]
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Workflow completed successfully!"
