name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-22.04
    outputs:
      digest: ${{ steps.builds.outputs.digest }}
    permissions:
      packages: write
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.0.2
        id: builds
        with:
          keep_versions: 50
          package: sync
          tag: ${{ github.event.number }}
          tag_fallback: latest
          triggers: ('sync/')

  deploy:
    name: Deploy
    needs: [deploys]
    uses: ./.github/workflows/.deploy.yml
    with:
      target: ${{ github.event.number }}
      triggers: ('sync/')

  results:
    name: PR Results
    if: always() && !failure()
    needs: [deploy]
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Workflow completed successfully!"
